addons:
  apt:
    packages:
    - libgmp-dev
after_success:
- | # Upload package to Hackage.
  if test "$TRAVIS_TAG" -a "$TRAVIS_OS_NAME" = linux
  then
    mkdir -p "$HOME/.stack/upload"
    echo "{ \"username\": \"$HACKAGE_USERNAME\", \"password\": \"$HACKAGE_PASSWORD\" }" > "$HOME/.stack/upload/credentials.json"
    stack upload --no-signature .
  fi
- | # Add compressed binary to GitHub release.
  if test "$TRAVIS_TAG" -a "$GITHUB_TOKEN"
  then
    gzip --best --to-stdout "$(stack path --local-install-root)/bin/github-release" > github-release.gz
    stack exec -- github-release upload \
      --token "$GITHUB_TOKEN" \
      --owner tfausak \
      --repo github-release \
      --tag "$TRAVIS_TAG" \
      --file github-release.gz \
      --name "github-release-$TRAVIS_TAG-$TRAVIS_OS_NAME.gz"
  fi
before_install:
- | # Install stack.
  if test ! -f "$HOME/.local/bin/stack"
  then
    URL="https://www.stackage.org/stack/$TRAVIS_OS_NAME-x86_64"
    curl --location "$URL" > stack.tar.gz
    gunzip stack.tar.gz
    tar -x -f stack.tar --strip-components 1
    mkdir -p "$HOME/.local/bin"
    mv stack "$HOME/.local/bin/"
  fi
cache:
  directories:
  - $HOME/.local/bin
  - $HOME/.stack
env:
  global:
  - HACKAGE_USERNAME=fozworth
  - secure: "pvj7lG56MmkhqdfI7CogwejCc5EtoVpyHTKGqzz7kaLiH6QpejQm5VWV8X+FkTE4LMFtQl6huTXU0tG2G9sCTRXsdE7Cx8Vb2chvC0vdWFHDwrO1N1g5apmU+KqY+BaOFp8nMwYSp5rtr0uPJuxlM8sZJjsWi5dyXsA/EHx8rjAi6s9E82W0qG0m+6jcWHI506n1YjC0DDZaf1cvVUpor6vEnV8A/DP7oJnDfEUx6sBmMAZIKiDY80yXqG703oAtLdShZhfkPdiW0G/5MUJrHcNpOmiDguFFmtP61hSr4oAiiaauXRgW893CceGQjGBsK+056R247A0wAK5ojog2oYqMWbT9MOL5V3iNMltm7wyS/XqOEblax812rNdIWlEw/kZhefBezfLXZ3GFNZoMLRcLzGfE+ETXoumpRMyo6pUKZvtvRhjfbhDLOdSG0d/9p/M5hMeRnK/1vsFiDLR38us43ojN4wFsS2rfkQ9J8j7wBpOqHBe5EnhtD/Fp9+dewax0eJqiiVapoSjiBaB96iMkbBffDaAANb0Dm+rhBv0x/hwDt/IfN5UXiUrOOAH0JjzMyLzulXx9NBrt+X51a8xBQJNyX+TCqT7t0/roC2NXlWRemQhrRUSJq2dUzNsXmtp3HHwj5B3ujPyWFZmt12/i6R00ocyTvzqptwXkwSA="
  - secure: "p/WdWeVPHdiamsaNubrNUfc4nPn/GmDotvcou+JX+OicQePYdr7+EJKLGuE1bmHV5brGA9ui8feqGTBQSKlrCet27cdrw0ofzoEVhjWgpP3qHhNN8urvsw7iHB3QQ1hQVQFeR6PYuTCwGptBEQ9O+WXhmChlHmxqlIxO40ARFRky4uD6v532ivLlvHJ0FywQRBS1CjWic5ULvr7EoTadTvxuGuHNOWp0/7SRFstG7jJNIxGeE7VEBgSwa4XQb7hoGnxl2rM9v7jU4/mkLMfex3Tch4u95KS04+6D4Yn6Y+/0bzEO9ESU4i8Iv+qyOQlml6rk54f/9IJwqpaGd7fbHDLi7IwWJXkNOBhj25VNYSbHpthoyGqz6HrmtBsG8DAkodTZHq/tRccHNOR5O9INSsfHcQnu52OH0/amkHzAtzjfwtA0PbiK5fBlMPCnakMgfs4aMNiPTGD6K2FH3IgEe1OTQuxGWUv0afQH+c4NprplbBCjKntww+cNd+79whx5D1tMVAS0L6LNw8v2fiOISN8jhsryMoOstn8iiFeA86yvrMOStpN4Sh4FZNG5QgE8QCOkfA4aXdf3gie7vTnCqyiT0BmTqto/9oCb6it+imGVQC7hmSHqmtdp+UCvdB/CHaCJN65dmrZlN5y5hNWXWrH6J1iZKL0nv0YopE1+4Pw="
language: c
os:
- linux
- osx
script:
- stack setup
- stack --no-terminal build --pedantic
- stack sdist
sudo: false
